# Generated by Django 4.2.11 on 2024-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0002_release_accent_color1_release_accent_color2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(default='EP', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(null=True),
        ),
    ]
