# Generated by Django 4.2.11 on 2024-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0005_alter_release_last_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='accent_color1',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color2',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color3',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color4',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
