# Generated by Django 4.2.11 on 2024-04-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0006_alter_release_accent_color1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='accent_color1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='accent_color4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='release',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='MusicReview.review'),
        ),
    ]
