# Generated by Django 4.2.11 on 2024-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0007_alter_release_accent_color1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
