# Generated by Django 4.2.11 on 2024-04-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0011_alter_review_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='cover_art',
            new_name='artist_photo',
        ),
        migrations.AddField(
            model_name='artist',
            name='accent_color1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='accent_color2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='accent_color3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='accent_color4',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
