# Generated by Django 4.2.11 on 2024-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0012_rename_cover_art_artist_artist_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('EP', 'EP'), ('Album', 'Album'), ('Mixtape', 'Mixtape'), ('Single', 'Single'), ('Compilation', 'Compilation'), ('Soundtrack', 'Soundtrack'), ('Live performance', 'Live performance')], max_length=100),
        ),
    ]
