# Generated by Django 4.2.11 on 2024-04-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0013_alter_release_release_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
