# Generated by Django 4.2.11 on 2024-04-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0014_song_is_explicit'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='released',
            field=models.DateField(null=True),
        ),
    ]
