# Generated by Django 4.2.11 on 2024-04-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0015_release_released'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSongInfo',
        ),
    ]
