# Generated by Django 4.2.11 on 2024-04-29 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicReview', '0016_delete_reportsonginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportartistinfo',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 19, 20, 16, 185986, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportreleaseinfo',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 19, 20, 20, 131719, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportreviewcontent',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 19, 20, 25, 687661, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
